---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
sections:
- type: directory
  path: " src/assets/content/about"
  label: Profile
  create: all
  match: "**/*"
- type: directory
  path: src/assets/content/news
  label: News
  create: all
  match: "**/*"
- type: directory
  path: src/assets/content/artwork
  label: Artwork
  create: documents
  match: "**/*"
  templates:
  - artwork
upload_dir: src/assets/content/images
public_path: "/src/assets/content/images"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: dest
  install_dependencies_command: npm install
  preview_docker_image: forestryio/node:12
  mount_path: "/srv"
  working_dir: "/srv"
  instant_preview_command: npm run develop
